//
//  LegalTabView.swift
//  SniffTest
//
//  Created by Alina Andreieva on 21/4/26.
//

import SwiftUI

struct LegalTabView: View {
    @State private var expandedSections: Set<String> = ["Eligibility and Use Conditions"]

    private let sections: [LegalSection] = [
        LegalSection(
            title: "Eligibility and Use Conditions",
            paragraphs: [
                "This platform is intended for users aged 16 and above. By accessing or using the application, users confirm that they meet this requirement.",
                "For users under the age of 16, the use of the platform is recommended under parental or educational supervision.",
                "Users agree to use the platform for educational purposes only. The platform shall not be used as a source of definitive information or relied upon for legal, professional, or decision-making purposes.",
                "The developers shall not be held responsible for any decisions made based on the interpretation or misuse of the outputs generated by the system."
            ]
        ),
        LegalSection(
            title: "Legal & Regulatory Framework",
            paragraphs: [
                "This platform operates at the intersection of artificial intelligence, freedom of expression, and information integrity. Its design is grounded in both European and Ukrainian legal standards.",
                "1. Freedom of Expression and Information Integrity",
                "The platform is developed in accordance with Article 10 of the European Convention on Human Rights, which guarantees the right to freedom of expression, including the freedom to receive and impart information without interference by public authorities.",
                "In Ukrainian legislation, this principle is reflected in Article 34 of the Constitution of Ukraine, which ensures freedom of thought and speech, as well as the right to freely collect, store, use, and disseminate information.",
                "The platform does not restrict or moderate content. Instead, it adopts a non-interventionist approach by strengthening users' ability to independently assess information, in line with European standards on countering disinformation through media literacy rather than censorship.",
                "2. Artificial Intelligence Regulation",
                "The system is designed in accordance with the EU Artificial Intelligence Act (Regulation (EU) 2024/1689).",
                "The platform does not fall within the category of high-risk AI systems, as defined in Article 6 and Annex III of the AI Act, since it does not perform automated decision-making producing legal effects or similarly significant impacts on individuals, materially influence the outcome of decision-making, or pose a significant risk to fundamental rights.",
                "At the same time, the system complies with core regulatory principles reflected in the AI Act, including transparency obligations, clarity of system limitations, and protection of human autonomy."
            ]
        ),
        LegalSection(
            title: "3. Data Protection and Privacy",
            paragraphs: [
                "Data processing is carried out in accordance with the General Data Protection Regulation, in particular Article 5 on principles of data processing and Article 6 on lawfulness of processing.",
                "In the Ukrainian context, the platform complies with the Law of Ukraine 'On Personal Data Protection' (Articles 6 and 7), which regulate lawful processing and protection of personal data.",
                "The system does not process sensitive categories of data, including biometric identification data, and limits data use strictly to functional purposes."
            ]
        ),
        LegalSection(
            title: "4. Ukrainian Legal Context and Information Security",
            paragraphs: [
                "The platform considers Ukrainian legislation on information and national security, including the Law of Ukraine 'On Information' and the Law of Ukraine 'On National Security of Ukraine'.",
                "In this context, disinformation constitutes a recognised challenge. However, the platform adopts a proportionate legal approach by enhancing information resilience through education rather than imposing restrictions on content."
            ]
        ),
        LegalSection(
            title: "5. Liability and Risk Mitigation",
            paragraphs: [
                "The platform functions as an educational and AI-assisted decision-support tool and does not establish factual truth, in line with the principle that AI systems should support human decision-making rather than replace it.",
                "In line with general principles reflected in European digital regulation, the system does not produce binding or legally relevant decisions, does not replace professional judgement, and clearly communicates the probabilistic nature of outputs.",
                "This approach reduces legal and ethical risks associated with misinformation, reputational harm, and overreliance on automated systems, in line with the objective of ensuring a high level of protection of fundamental rights.",
                "In addition to the risks outlined above, the platform also considers technical and algorithmic risks inherent to AI systems, particularly those based on machine learning models such as Support Vector Machines and transformer-based models.",
                "These include algorithmic bias, false positives and false negatives, overgeneralization, dataset limitations, lack of full explainability, automation bias, and risk of misuse.",
                "These risks are mitigated through transparency, probabilistic outputs, clear disclaimers, and a design focused on supporting rather than replacing human judgment."
            ]
        ),
        LegalSection(
            title: "6. Ethical and Legal Design Principles.",
            paragraphs: [
                "The platform is guided by the following legally relevant principles: neutrality, transparency, user autonomy, and educational purpose.",
            ]
        ),
        LegalSection(
            title: "7. Liability and Responsibility",
            paragraphs: [
                "The platform operates as an educational and AI-assisted decision-support tool and does not produce legally binding outcomes or definitive assessments of truth.",
                "Responsibility is distributed as follows: the provider is responsible for the design, transparency, and lawful functioning of the system, while the user or deployer is responsible for the interpretation and use of outputs, especially in external or professional contexts.",
                "In line with the EU Artificial Intelligence Act, liability does not arise from the mere use of AI, but from non-compliance with legal obligations, including misleading design or manipulative practices.",
                "Where user data is processed, responsibility also arises under the General Data Protection Regulation, in particular lawful processing requirements and data protection principles.",
                "Under Ukrainian law, general liability follows from the obligation to compensate damage caused by unlawful actions under Article 1166 of the Civil Code of Ukraine, while freedom of information is guaranteed under Article 34 of the Constitution of Ukraine.",
                "This allocation of responsibility reflects a role-based approach to AI governance and ensures legal clarity while preserving user autonomy and freedom of expression."
            ]
        )
    ]

    var body: some View {
        NavigationStack {
            ZStack {
                AppTheme.background
                    .ignoresSafeArea()

                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        Text("Legal")
                            .font(.largeTitle.bold())

                        Text("Open each section to read the full text.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)

                        ForEach(sections) { section in
                            LegalDropdownSection(
                                section: section,
                                isExpanded: expandedSections.contains(section.id)
                            ) {
                                toggle(section.id)
                            }
                        }
                    }
                    .padding(24)
                }
            }
        }
    }

    private func toggle(_ id: String) {
        if expandedSections.contains(id) {
            expandedSections.remove(id)
        } else {
            expandedSections.insert(id)
        }
    }
}

private struct LegalSection: Identifiable {
    let title: String
    let paragraphs: [String]

    var id: String { title }
}

private struct LegalDropdownSection: View {
    let section: LegalSection
    let isExpanded: Bool
    let action: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Button(action: action) {
                HStack(spacing: 12) {
                    Text(section.title)
                        .font(.headline)
                        .multilineTextAlignment(.leading)

                    Spacer()

                    Image(systemName: "chevron.down")
                        .rotationEffect(.degrees(isExpanded ? 180 : 0))
                        .foregroundStyle(.indigo)
                }
                .padding(20)
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)

            if isExpanded {
                VStack(alignment: .leading, spacing: 14) {
                    ForEach(Array(section.paragraphs.enumerated()), id: \.offset) { _, paragraph in
                        Text(paragraph)
                            .font(.body)
                            .foregroundStyle(.primary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
                .padding(.horizontal, 20)
                .padding(.bottom, 20)
                .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .background(AppTheme.quizContainer, in: RoundedRectangle(cornerRadius: 24, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .stroke(Color.black.opacity(0.08), lineWidth: 1)
        )
        .animation(.easeInOut(duration: 0.2), value: isExpanded)
    }
}
