//
//  LegalTabView.swift
//  SniffTest
//
//  Created by Alina Andreieva on 21/4/26.
//

import SwiftUI

struct LegalTabView: View {
    @State private var expandedSections: Set<String> = ["Eligibility and Use Conditions"]

    private let sections: [LegalSection] = [
        LegalSection(
            title: "Eligibility and Use Conditions",
            paragraphs: [
                "This platform is intended for users aged 16 and above. By accessing or using the application, users confirm that they meet this requirement.",
                "For users under the age of 16, the use of the platform is recommended under parental or educational supervision.",
                "Users agree to use the platform for educational purposes only. The platform shall not be used as a source of definitive information or relied upon for legal, professional, or decision-making purposes.",
                "The developers shall not be held responsible for any decisions made based on the interpretation or misuse of the outputs generated by the system."
            ]
        )
    ]

    var body: some View {
        NavigationStack {
            ZStack {
                AppTheme.background
                    .ignoresSafeArea()

                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        Text("Legal")
                            .font(.largeTitle.bold())

                        Text("Open each section to read the full text.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)

                        ForEach(sections) { section in
                            LegalDropdownSection(
                                section: section,
                                isExpanded: expandedSections.contains(section.id)
                            ) {
                                toggle(section.id)
                            }
                        }
                    }
                    .padding(24)
                }
            }
        }
    }

    private func toggle(_ id: String) {
        if expandedSections.contains(id) {
            expandedSections.remove(id)
        } else {
            expandedSections.insert(id)
        }
    }
}

private struct LegalSection: Identifiable {
    let title: String
    let paragraphs: [String]

    var id: String { title }
}

private struct LegalDropdownSection: View {
    let section: LegalSection
    let isExpanded: Bool
    let action: () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Button(action: action) {
                HStack(spacing: 12) {
                    Text(section.title)
                        .font(.headline)
                        .multilineTextAlignment(.leading)

                    Spacer()

                    Image(systemName: "chevron.down")
                        .rotationEffect(.degrees(isExpanded ? 180 : 0))
                        .foregroundStyle(.indigo)
                }
                .padding(20)
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)

            if isExpanded {
                VStack(alignment: .leading, spacing: 14) {
                    ForEach(Array(section.paragraphs.enumerated()), id: \.offset) { _, paragraph in
                        Text(paragraph)
                            .font(.body)
                            .foregroundStyle(.primary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
                .padding(.horizontal, 20)
                .padding(.bottom, 20)
                .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .background(AppTheme.quizContainer, in: RoundedRectangle(cornerRadius: 24, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .stroke(Color.black.opacity(0.08), lineWidth: 1)
        )
        .animation(.easeInOut(duration: 0.2), value: isExpanded)
    }
}
